language: java
sudo: required
jdk:
- openjdk8
services:
- docker
script:
- "./.travis/build.sh"
branches:
  only:
  - master
env:
  global:
  - secure: G6APN8bBX1BTfpGpteBRbUyGsEcb8Abv36cekg72USOczKSa+bgxAHeCYHH6gZAcyz4iiEOGYRsnfSYWe6EsS7t/k6kqIntchys6nEyGy3VbJwEiiVXsGOypVuBpAg40MkSwTw7p0FGJ+GQ1Jm75UDwJLR+dKHTX0W5J1WOcwL6jtAXjuwtAWeKk7CuIPzjAN4hbfBUxBHqPhztHD/IE9wJOoMl7rBv7lrhZihkYsjwv8RRB7XEELsORTkaUcjSzTLa6h4LDbJlSh2BIUFRg9z5KkLHXSJmusbJDyJQge9pBbaNd0ul3z48sDS5cSbAwtfDeZHFcGALA4IhZiAuB/I1kbwwRovruw6/GAesxFITZXLgCO3sNRH71h2zls/D72+xGNs2I8DlHapr6Ls708YKqA2crPtex9bAbzPXQAVFHfi1ovupDA77x7h4CM8nlD2tN3MpTtSvxYxavlx7C67/IUS32kzyfmPRhYqEpIgFUz+FJjJK38yzx9vStCPmLKNZfOmp4zB0arfsJNiQ1/HGmlaohvaC3i+dJ2m0Km3y3Iu6nkOUY22z5BR6eAd3ZJvyis0R4j8GdMKUkTKrzgZknb66zwy7v8wqYpqmnO9gd9NSDCzewPYGsrPtKul+fVXeNehEYT6ylrZ+hWd+grBvV5EpgRWh5PMQhEB/4nPM=
  - secure: Ec5UyYlfvK4UrJSzhqdQH5kuDmCo6LF7PUV8t98F8akmeuaFlAnCeVm6dltOwoDWac5GfhScRmnD90lwmdZKjKnDbanpAZQ3vEdTX6F+4ewzDTiF+yf/BU25BPT/Xo78tO+8VC4EhHjkjpb4iAj67QklWfx6/03vtrmmW7rna69f6vACejyWRfh7S2n6moLlVEjUMe6SxTRo24a2fN3vJk4UcyM1YDqDYMOMiIWBF8hoECgY8pPET1tznqUh7TMNboSpqW9SsqrzS2FTqA3IeScLekqKSJOurq3SABV2oTBAh85hkmRONEMnpQClTYxRYLMSI19+QzwfMMnr9IRlvsdQ7BqfLF73CxlHwNiiVi2PSe3t5Sif3fW/6o+dsXVE+E2JxoE4Mj1JOAjFqi5zDp1Gu3j+8HrKezVS09Y230+lDaciCQtfENVqS8zxavUGl7kOyqiqOLLU619vpmbF3S5CPvKx4RhXCsnLtp1HZVYvFHDdaSVbGZZPuCjCCpXBsq+a/439/4jwj8Qa9Riz+l+9vF9DTtjwsYFvcyGZGsnrwEI1hJpjCH0fSF2gj+6qwqYBHVg/kVYGzUs+i3patZqkPrRAlBnKuThOhUHR1IiPcMxjitc75TgW48/JnaTBrhHcvuT7kXcXFj0pjpBIzKttXiJ2Gwprukr/x3Bc++U=
