# Copyright 2017 Heptio Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: openshift-event-source
  namespace: myproject
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: openshift-event-source
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: openshift-event-source
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-event-source
subjects:
- kind: ServiceAccount
  name: openshift-event-source
  namespace: myproject
---
apiVersion: v1
data:
  config.json: |-
    {
      "sink": "http",
      "httpSinkUrl": "http://openshift-cloud-event-source/post/heptio",
      "httpSinkBufferSize": 1500,
      "httpSinkDiscardMessages": true
    }
kind: ConfigMap
metadata:
  name: openshift-event-source-cm
  namespace: myproject
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: openshift-event-source
  namespace: myproject
  labels:
    app: openshift-event-source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openshift-event-source
  template:
    metadata:
      labels:
        app: openshift-event-source
        tier: control-plane-addons
    spec:
      containers:
      - name: kube-openshift-event-source
        image: gcr.io/heptio-images/eventrouter:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-volume
          mountPath: /etc/eventrouter
      serviceAccount: openshift-event-source
      volumes:
      - name: config-volume
        configMap:
          name: openshift-event-source-cm